### PR TITLE
Fix timezone, week start and count

### PR DESCRIPTION
**Pull request by jeromecombes**
Hi,

I  added some capabilities to your helpful and wonderful project : 
- Taking into account timezones
- Taking into account the WKST setting ( see WKST example on  http://www.kanzaki.com/docs/ical/rrule.html)
- Stop when RRULE[COUNT] is reached (There's a mistake in your computation, I didn't want to change all, therefore I just added some breaks but we can do something better).

If you want to merge my work...

Don't hesitate to ask me if you have questions.

Best,
Jérôme

### CODE REVIEW

**Comment by u01jmg3** [comment]
Thanks for this - the changes look to be very useful

Before I can merge, I will have to test on my end. I am seeing some funkiness with the indentation - think your editor must be set to tabs whereas this project uses 4 spaces as specified in our [contributing guidelines](https://github.com/johngrogg/ics-parser/blob/master/CONTRIBUTING.md). (Please pay particular attention to guideline 3.)

**Comment by jeromecombes** [comment]
Hi,

Sorry for the indentation.
I'll change my editor configuration before next changes.
Tell me if you want me to change that for the lasts modifications.

**Comment by u01jmg3** [comment]
Yes please commit again correcting the indention, etc. based on the contributing guidelines. Thanks

**Comment by jeromecombes** [comment]
Hi,

I opened 3 issues in adequation with my pull request. (I didn't see the one about the timezone already opened, sorry).
I'll work later on correcting the indentation, etc.

A quick question : 
Is there a reason that you don't use strtotime instead of the iCalDateToUnixTimestamp method ?
I can't see what this method gives more.
strtotime works fine with timezone and converts properly ICS date format to an unix timestamp.

examples : 
strtotime("20160707T150000Z") gives the 7/7/2016 15:00 UTC timestamp
strtotime("20160707T150000") gives the 7/7/2016 15:00 local time timestamp (timezone define in php.ini or by date_timezone_set)

**Comment by u01jmg3** [comment]
> I opened 3 issues in adequation with my pull request. (I didn't see the one about the timezone already opened, sorry).

It's a little late opening issues after committing fixes because normally you would reference in your commit message the issue you are targeting.

--

> Is there a reason that you don't use strtotime instead of the iCalDateToUnixTimestamp method ?
I can't see what this method gives more.
strtotime works fine with timezone and converts properly ICS date format to an unix timestamp.

No doubt it's historical and a decision made by the original author

**Comment by u01jmg3** [comment]
Closing in place of #70

**Pull request closed without merging**
