### PR TITLE
Code Fix

### PR DESCRIPTION
**Pull request by Bratzmeister**
Line 21: Syntax Error in reset()-functions parameters (tested on PHP 5.3.10)

### CODE REVIEW

**Comment by u01jmg3** [comment]
This isn't correct:

> Warning: reset() expects parameter 1 to be array, null given in C:\Program Files\WAMP Server\www\~repositories\ics-parser\example.php on line 21

**Comment by Bratzmeister** [comment]
I get a similar Fatal Error (syntax error) on Apache on Ubuntu with the way you put it.
It works just as fine with my change.

**Comment by u01jmg3** [comment]
What about swapping completely to `$events[0]['DTSTART']`?

**Comment by Bratzmeister** [comment]
I think option 2 is the nicer/cleaner approach. Both work for me

**Comment by u01jmg3** [comment]
Okay, amend your PR to option 2 and I'll merge

**Comment by u01jmg3** [comment]
Not sure why you haven't just modified this same PR instead of opening a new one but well well

**Comment by Bratzmeister** [comment]
Well actually I am very new to Github and I didn't find the function to
do it properly. When it was sent it was too late :-S

**Pull request closed without merging**
