### PR TITLE
Fix for Issue #42

### PR DESCRIPTION
**Pull request by Bratzmeister**
Added timezone support for recurring events and thus fixing issue #42 .

Additionally fixed a typo in a variable name.

### CODE REVIEW

**Comment by u01jmg3** [comment]
Thanks for the PR and spotting the spelling error. However, I do have a few concerns with your PR.

Your commit messages don't appear to match the file changes and I'm not familiar with the language you've used in places (e.g. 'aktuelle'). As this library is written in English for consistency we need to keep with that.

I know you were having a problem with week start but forcing Monday rather than Sunday as the first day of the week as it fits your use case is not the best course of action. Instead you should parse `WKST` if it is set and then adjust to use Monday accordingly.

Lastly, your fix using `$gmt_offset` will only grab the timezone from your installation of PHP and won't necessarily match that of the iCal file you're attempting to parse. Instead the timezone should be taken from the iCal file itself if it is present.

**Comment by Bratzmeister** [comment]
Hey, thanks for your review. The points you listed make sense and here are my words:

Regarding the commit messages, I am sorry I messed them up a bit. It was my local git repository and the fixes happened in the first commit which I gave a dummy name (aktuelle version means "initial version" in this case). I will find a way to change the commit messages and send them anew. 

Using Sunday as week start is conflicting with PHP and the `.ics` because both go with ISO-8601(https://en.wikipedia.org/wiki/ISO_8601#Week_dates) from what I learned in my research looking for the error. Anyways, taking the value from WKST is a good idea, since I also learnt that some arabic countries' first day of week is saturday. I will make Monday the default then.

About the `$gmt_offset` you are right but I am not sure if every `.ics` has their timezone included. Will also make a check for that.

**Comment by Bratzmeister** [comment]
If you want I can create a new pull request with fixed messages

**Comment by Bratzmeister** [comment]
I made major changes to the comment above, if you haven't reread it please take a look.

**Pull request closed without merging**
